<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Ellipse extends CI_Model {

	public function __construct() 
	{
		parent::__construct();
		$this->load->database('ellipse', TRUE);
	}

	public function load_sdm()
	{
		$query = $this->db->query("
			SELECT 
			    M.*, 
			    CS.RESOURCE_TY,
			    (SELECT TABLE_DESC FROM ELLIPSE.MSF010 WHERE TABLE_TYPE = 'TT' AND TABLE_CODE = CS.RESOURCE_TY) AS SKILL_COMP,
			    CS.COMPTCY_LEVEL, 
			    C.COMPTCY_DESC,
			    CS.GAINED_DATE, 
			    CS.REV_EXP_DATE AS EXP_DATE,
			    CASE WHEN TRIM(CS.REV_EXP_DATE) IS NOT NULL AND TRIM(CS.REV_EXP_DATE) <> '00000000' THEN FLOOR(MONTHS_BETWEEN(TO_DATE(CS.REV_EXP_DATE,'YYYYMMDD'),SYSDATE)) ELSE 100 END AS SISA,
			    CS.INSTITUTE AS KODE_LEMBAGA, 
			    DECODE(
			        TRIM(INSTITUTE), 
			        '',
			        (SELECT TRIM(STD_VOLAT_2) FROM ELLIPSE.MSF096_STD_VOLAT WHERE STD_TEXT_CODE = 'P5' AND  TRIM(STD_KEY) = TRIM(EMPLOYEE_ID) || '    ' || TRIM(RESOURCE_TY)),
			        (SELECT TABLE_DESC FROM ELLIPSE.MSF010 WHERE TABLE_TYPE = 'RESI' AND TABLE_CODE = INSTITUTE)
			    ) AS NAMA_LEMBAGA
			FROM (
			    SELECT
			        DISTINCT TRIM(A.EMPLOYEE_ID) AS PRIMARY_KEY,
			        TRIM(TRIM(A.FIRST_NAME) || ' ' || TRIM(A.SURNAME)) AS NAMA_LENGKAP,
			        TRIM(D.PHYSICAL_LOC) AS KODE_UNIT,
			        TRIM(B.WORK_LOC) AS KODE_SUBDIT,
			        TRIM((SELECT TABLE_DESC FROM ELLIPSE.MSF010 WHERE TABLE_TYPE = '+DIV' AND LPAD(TABLE_CODE, 2) = SUBSTR(C.POSITION_ID, 1, 2))) AS DIV,
			        (SELECT TRIM(TABLE_DESC) FROM ELLIPSE.MSF010 WHERE TABLE_TYPE LIKE 'PHYL' AND TABLE_CODE = PHYSICAL_LOC) AS LOKASI_UNIT,
			        (SELECT TRIM(TABLE_DESC) FROM ELLIPSE.MSF010 WHERE TABLE_TYPE LIKE 'WRKL' AND TABLE_CODE = B.WORK_LOC) AS SUBDIT,
			        TRIM(EMAIL_ADDRESS) AS EMAIL,
			        TRIM(POS_TITLE) AS POSISI,
			        TRIM(B.PREV_EMP_ID) AS NID,
			        G1.COMPTCY_LEVEL AS KODE_GRADE,
			        G2.COMPTCY_DESC AS GRADE
			    FROM ELLIPSE.MSF810 A
			    LEFT OUTER JOIN ELLIPSE.MSF760 B ON A.EMPLOYEE_ID=B.EMPLOYEE_ID
			    LEFT OUTER JOIN ELLIPSE.MSF878 C ON A.EMPLOYEE_ID=C.EMPLOYEE_ID
			    LEFT OUTER JOIN ELLIPSE.MSF870 P ON C.POSITION_ID=P.POSITION_ID
			    LEFT OUTER JOIN ELLIPSE.MSF829 D ON A.EMPLOYEE_ID=D.EMPLOYEE_ID
			    LEFT JOIN ELLIPSE.MSF765 G1 ON G1.EMP_RES_IND = 'C' AND TRIM(A.EMPLOYEE_ID)=TRIM(G1.EMPLOYEE_ID) AND G1.RESOURCE_TY='GG3P'
			    LEFT JOIN ELLIPSE.MSF737 G2 ON G1.COMPTCY_LEVEL=G2.COMPTCY_LEVEL
			    WHERE C.POS_STOP_DATE = '00000000'
			    AND C.PRIMARY_POS = '0'
			    AND D.END_DATE = '00000000'
			    AND B.EMP_STATUS LIKE 'A'
			) M 
			JOIN MSF765 CS ON TRIM(CS.EMPLOYEE_ID)=M.PRIMARY_KEY AND CS.RESOURCE_TY NOT LIKE 'C5%' 
			LEFT JOIN ELLIPSE.MSF737 C ON CS.COMPTCY_LEVEL=C.COMPTCY_LEVEL AND CS.RESOURCE_TY=C.RESOURCE_TYPE
			WHERE CS.EMP_RES_IND='C' AND (CS.RESOURCE_TY LIKE 'C1%' OR CS.RESOURCE_TY LIKE 'C2%' OR CS.RESOURCE_TY LIKE 'C3%')
			");
		
		return $query->result_array();
	}

}
